version: '3.8'

services:
  activemq:
    container_name: activemq-fusedev
    image: webcenter/activemq:5.14.3
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    networks:
      - rhf-fusedev
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: password
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: password
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: password
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
    volumes:
      - activemq-fusedev-log:/var/log/activemq
      - activemq-fusedev-data:/data/activemq
      - activemq-fusedev-conf:/opt/activemq/conf
  jaeger:
    container_name: jaeger-fusedev
    image: jaegertracing/all-in-one:1.21
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - rhf-fusedev
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    volumes:
      - jaeger-fusedev-tmp:/tmp

networks:
  rhf-fusedev:
    name: rhf-fusedev

volumes:
  activemq-fusedev-log:
    name: activemq-fusedev-log
  activemq-fusedev-data:
    name: activemq-fusedev-data
  activemq-fusedev-conf:
    name: activemq-fusedev-conf
  jaeger-fusedev-tmp:
    name: jaeger-fusedev-tmp
